        // 夏乌拉追随者 节点
        "Ravenous Doubts": "饑渴的疑問",
        "Consuming Questions": "吞噬疑問",
        "Chayula\"s Gift": "夏烏拉的禮物",
        "Reality Rending": "現實撕裂",
        "Waking Dream": "夢境",
        "Lucid Dreaming": "清醒夢",
        "Embrace the Darkness": "擁抱黑暗",
        "Grasp of the Void": "虛空之握",
        "Inner Silence": "內心寧靜",
        // 祈求者 节点
        "…and Protect me from Harm": "……名為無處的家",
        // 猎巫人 节点
        "Weapon Master": "驅散惡靈",
        "Pitiless Killer": "法官、陪審團與劊子手",
        "Judge, Jury, and Executioner": "委任殺手",
        "Witchbane": "妨礙司法",
        "No Mercy": "播種不諧",
        "Obsessive Rituals": "清教徒知識",
        "Ceremonial Ablution": "儀式淨身",
        "Zealous Inquisition": "神聖授權",
        // 古灵使徒斗士 节点
        "Crystalline Potential": "結晶潛能",
        "Implanted Gems": "植入寶石",
        "Advanced Thaumaturgy": "進階奇術",
        "Integrated Efficiency": "整合效率",
        "Gem Studded": "鑲嵌的寶石",
        "Thaumaturgical Infusion": "奇術注入",
        "Adaptive Capability": "應變能力",
        "Enhanced Effectiveness": "強化效果",
        "Reduced Attribute Requirements": "减少能力值需求",
        "Equipment and Skill Gems have 4% reduced Attribute Requirements": "装备和技能宝石有4%的能力值需求减少",
        // 风暴编织者 节点
        "Constant Gale": "不變勁風",
        "Force of Will": "意志之力",
        "Mind Over Matter": "心靈昇華",
        "Scouring Winds": "橫掃之風",
        "Overexposure": "過度曝曬",
        "Heavy Snows": "狂風暴雪",
        "Shaper of Winter": "寒冬雕塑者",
        "Strike Twice": "二重打擊",
        "Shaper of Storms": "風暴雕塑者",
        "Heart of the Storm": "暴風之心",
        "Tempest Caller": "暴風召喚者",
        "Rain Dancer": "雨之舞者",
        // 塑时术师 节点
        "Now and Again": "再度上演",
        "Unbound Encore": "無縛安可",
        "Ultimate Command": "終極指令",
        "Footprints in the Sand": "沙中足跡",
        "Quicksand Hourglass": "流沙沙漏",
        "Apex of the Moment": "巔峰時刻",
        "Circular Heartbeat": "心跳循環",
        "The Rapid River": "急流",
        // 战争使者 节点
        "Anvil\"s Weight": "玉石切割者的刀刃",
        "Imploding Impacts": "玉石切割者的圖釘",
        "Jade Heritage": "玉石切割者的魔偶",
        "Answered Call": "玉石薩滿的指引",
        "Wooden Wall": "玉石薩滿的保護",
        "Renly\"s Training": "戰場大師的路障",
        "Turtle Charm": "戰場大師的烏龜聖符",
        "Warcaller\"s Bellow": "戰爭呼喚者的咆哮",
        "Greatwolf\"s Howl": "戰爭呼喚者的戰角",
        // 泰坦 节点
        "Stone Skin": "無敵",
        "Earthbreaker": "無與倫比",
        "Ancestral Empowerment": "無與倫比",
        "Colossal Capacity": "巨量承載",
        "Hulking Form": "不可侵",
        "Crushing Impacts": "不敗戰士",
        "Surprising Strength": "勢不可擋",
        "Mysterious Lineage": "傷害免疫",
        // 锐眼 节点
        "Endless Munitions": "無限彈藥",
        "Eagle Eyes": "潛意識",
        "Point Blank": "零點射擊",
        "Far Shot": "遠射",
        "Gathering Winds": "集風",
        "Wind Ward": "風之守衛",
        "Acrobatics": "移形換影",
        "Avidity": "貪慾",
        "Thrilling Chase": "爆發",
        "Called Shots": "預告射擊",
        // 追猎者 节点
        "Connected Chemistry": "連鎖化學",
        "Fine Belt w/Flask Mods": "精緻腰帶/带药剂词缀",
        "Enduring Elixirs": "耐久靈藥",
        "Saturated Ultimate Life Flask of the Sylvan":"森林的饱和終極生命藥劑",
        "Hale Traveller": "健壯旅人",
        "Heavy Drinker": "重度飲用者",
        "Contagious Contamination": "汙穢傳染",
        "Overwhelming Toxicity":"懾人劇毒",
        "Building Toxins":"蓄積毒素",
        "Brew Concoction": " 釀造靈藥",
        "Bleeding Concoction":"流血混合物",
        "Explosive Concoction":"爆裂物",
        "Shattering Concoction":"粉碎混合物",
        "Fulminating Concoction":"烈性混合物",
        "Poisonous Concoction":"毒藥",
        "Arcane Alchemy":"秘能鍊金術",
        "Traveller\"s Wisdom":"旅者的智慧",
        "Passive Points":"天賦點數",
        "Running Assault":"衝刺突擊",
        "Relentless Pursuit":"無情追獵",
        // 命源法师 节点
        "Sanguimancy":"占血術",
        "Vitality Siphon":"活力虹吸",
        "Open Sores":"開瘡",
        "Blood Barbs":"鮮血荊棘",
        "Gore Spike":"血棘",
        "Sunder the Flesh":"碎裂血肉",
        "Grasping Wounds":"緊扼傷口",
        "Crimson Power":"緋紅之力",
        // 驱炎使 节点
        "Altered Flesh":"變形肉體",
        "Beidat\"s Gaze":"貝達特之視",
        "Beidat\"s Will":"貝達意志",
        "Beidat\"s Hand":"貝達特之手",
        "Demonic Possession":"惡魔附身",
        "Mastered Darkness":"黑暗精通",
        "Pyromantic Pact":"火祭協議",
        "Bringer of Flame":"火焰呼喚者",
        "Seething Body":"沸騰軀體",
        "Loyal Hellhound":"忠誠獄犬",
        "Grinning Immolation":"邪惡焚化",
